from enum import Enum

class IntentType(Enum):
    DATA_UNDERSTANDING = "DATA_UNDERSTANDING"
    FEATURE_ASSESSMENT = "FEATURE_ASSESSMENT"
    DATA_HETEROGENEITY_ASSESSMENT = "DATA_HETEROGENEITY_ASSESSMENT"
    MODEL_EXPLANATION = "MODEL_EXPLANATION"
    MODEL_SELECTION = "MODEL_SELECTION"