[tool.poetry]
name = "kmds"
version = "0.2.16"
description = "This is a package that helps data scientists and data analysts to capture notes while they work through data science tasks. The captured tasks can then be searched and analyzed."
authors = ["Rajiv Sambasivan <rajiv.sambasivan@r2-ds.com>"]
license = "Apache 2.0"
readme = "README.md"


[tool.poetry.dependencies]
python = ">=3.10,<3.11"
owlready2 = "^0.46"
rdflib = "^7.5.0"
Flask = "^3.0.3"
pytest = "^8.3.0"
PyYAML = "^6.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "boxsdk>=10.3.0",
    "flask>=3.1.2",
    "google-genai>=1.60.0",
    "importlib-resources>=6.5.2",
    "ipython>=9.9.0",
    "jupyter>=1.1.1",
    "jupyter-ai[all]>=2.31.7",
    "jupyterlab>=4.5.3",
    "langchain-google-vertexai>=2.1.2",
    "minio>=7.2.20",
    "notebook>=7.5.3",
    "openml>=0.15.1",
    "owlready2>=0.49",
    "plotly>=6.5.2",
    "prefect>=3.6.13",
    "pytest>=9.0.2",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
    "rdflib>=7.5.0",
    "scikit-learn>=1.8.0",
    "sphinx>=9.1.0",
    "sphinx-rtd-theme>=3.1.0",
]

[[tool.poetry.source]]
name = "default"
url = "https://test.pypi.org/simple/"
priority = "primary"


[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

